import 'package:flutter/material.dart';

import '../app/app_scope.dart';

extension StringLocalization on String {
  String tr(BuildContext context) {
    final scope = AppScope.of(context);
    if (scope.locale.languageCode != 'ar') return this;
    return AppStrings.ar[this] ?? this;
  }
}

class AppStrings {
  static const Map<String, String> ar = {
    'Smart Fit': 'سمارت فيت',
    'Get Started': 'ابدأ الآن',
    'Log In': 'تسجيل الدخول',
    'Settings': 'الإعدادات',
    'Log out': 'تسجيل خروج',
    'Log out?': 'هل تريد تسجيل الخروج؟',
    'Cancel': 'إلغاء',
    'You will be returned to the login screen.': 'سيتم إعادتك إلى شاشة تسجيل الدخول.',
    'Meal Plan': 'خطة الوجبات',
    'Achievements': 'الإنجازات',
    'Start InBody Scan': 'ابدأ فحص InBody',
    'Nutrition': 'التغذية',
    'Progress & Analytics': 'التقدم والتحليلات',
    'AI Coach': 'المدرب الذكي',
    'Upload your InBody\\nscan': 'ارفع فحص\\nInBody الخاص بك',
    'Supports InBody 120, 270, and 570': 'يدعم أجهزة InBody 120, 270 و 570',
    'Analyzing your InBody scan…': 'جاري تحليل الفحص...',

    'Or upload from gallery': 'أو ارفع من المعرض',
    'Take a photo': 'التقط صورة',
    'Extract InBody Scan': 'استخراج بيانات الفحص',
    'Scan uploaded successfully\\n': 'تم رفع الفحص بنجاح\\n',
    'Verify & Correct Values': 'تحقق وصحح القيم',
    'Generating your plans': 'جاري إنشاء خططك',
    'Your AI plan is being generated...': 'جاري إنشاء خطتك بالذكاء الاصطناعي...',
    'Analyzing your body data': 'جاري تحليل بيانات جسمك',
    'Go to Dashboard': 'الذهاب إلى لوحة التحكم',
    'Your personalised plans': 'خططك المخصصة',
    'Generated from your InBody scan and AI engines.': 'تم الإنشاء بناءً على فحص InBody ومحركات الذكاء الاصطناعي.',
    'Could not load dashboard data. Check your connection.': 'تعذر تحميل بيانات لوحة التحكم. تحقق من اتصالك.',
    'Coach is typing…': 'المدرب يكتب...',
    'Could not load meal plan. Check your connection.': 'تعذر تحميل خطة الوجبات. تحقق من اتصالك.',
    'Could not load hydration data.': 'تعذر تحميل بيانات الترطيب.',
    'Could not log hydration. Try again.': 'تعذر تسجيل الترطيب. حاول مرة أخرى.',
    'Log': 'تسجيل',
    'Could not log meal. Try again.': 'تعذر تسجيل الوجبة. حاول مرة أخرى.',
    'Try again': 'حاول مرة أخرى',
    'Could not load workout plan. Check your connection.': 'تعذر تحميل خطة التمارين. تحقق من اتصالك.',
    'Workout logged!': 'تم تسجيل التمرين!',
    'Meal logged!': 'تم تسجيل الوجبة!',
    'Landing': 'الرئيسية',
    'Share Recipe': 'مشاركة الوصفة',
    'Print Recipe': 'طباعة الوصفة',
    'Print PDF': 'طباعة PDF',
    'Share PDF': 'مشاركة PDF',
    'Report an issue': 'الإبلاغ عن مشكلة',
    'Swap': 'تبديل',
    'Total Calories': 'إجمالي السعرات',
    'PROTEIN': 'بروتين',
    'CARBS': 'كربوهيدرات',
    'FAT': 'دهون',
    'PER SERVING': 'لكل حصة',
    'Ingredients': 'المكونات',
    'Training Advice': 'نصائح التدريب',
    'Finish Setup': 'إنهاء الإعداد',
    'Your preferences': 'تفضيلاتك',
    'Select Theme': 'اختر المظهر',
    'Light Mode': 'الوضع الفاتح',
    'Dark Mode': 'الوضع الداكن',
    'System Default': 'الوضع الافتراضي',
    'Back': 'رجوع',
    'Confirm Extraction for Generating Plans': 'تأكيد الاستخراج لإنشاء الخطط',
    'Tips for success': 'نصائح للنجاح',
    'Ensure lighting is even and text is sharp for the AI to analyze your metrics accurately.': 'تأكد من أن الإضاءة متساوية والنص واضح ليقوم الذكاء الاصطناعي بتحليل بياناتك بدقة.',
    'Align the scan within the\\ngrid': 'قم بمحاذاة الفحص داخل\\nالشبكة',
    'No scan data yet': 'لا توجد بيانات فحص بعد',
    'No achievements yet': 'لا توجد إنجازات بعد',
    'Track your fitness journey and upcoming\\nmilestones.': 'تتبع رحلة لياقتك والمعالم القادمة.',
    'Complete workouts, log meals, and\\nstay consistent to earn badges.': 'أكمل التمارين وسجل الوجبات وكن ملتزماً لكسب الشارات.',
    'Before / After': 'قبل / بعد',
    'VS PREVIOUS SCAN': 'مقابل الفحص السابق',
    'Found at the top of your InBody printout, usually under personal details.': 'موجود في الجزء العلوي من طباعة InBody الخاصة بك، عادةً تحت التفاصيل الشخصية.',
    'Measures cellular health and integrity.': 'يقيس صحة وسلامة الخلايا.',
    'Represents body water balance and recovery status.': 'يمثل توازن ماء الجسم وحالة التعافي.',
    'Skeletal Muscle Mass used to estimate strength capacity.': 'كتلة العضلات الهيكلية المستخدمة لتقدير سعة القوة.',
    'Estimated calories burned at rest.': 'السعرات الحرارية المقدرة المحروقة في وقت الراحة.',
    'Fat-Free Mass of the trunk area.': 'الكتلة الخالية من الدهون في منطقة الجذع.',
    'Total fluid in the body.': 'إجمالي السوائل في الجسم.',
    'Total mass of fat in the body.': 'الكتلة الإجمالية للدهون في الجسم.',
    'Percentage of total body weight that is fat.': 'النسبة المئوية لوزن الجسم الإجمالي التي تتكون من الدهون.',
    'InBody metric value.': 'قيمة مقياس InBody.',
  };
}
