import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/plan_result.dart';

class PdfGenerator {
  /// Mapped teal branding color for the PDF layout.
  static const _brandTealHex = '#008080';
  static const _lightBgHex = '#F4F7F6';

  /// Generates the printable PDF document bytes.
  static Future<Uint8List> generatePlanPdf(
    PlanResult plan, {
    String userName = 'SmartFit User',
    bool isArabic = false,
  }) async {
    final doc = pw.Document(
      title: 'SmartFit Personalized Report',
      author: 'SmartFit AI',
    );

    // Resolve fonts dynamically using Google Fonts to support clean Unicode and Arabic text rendering.
    final primaryFont = await PdfGoogleFonts.cairoRegular();
    final primaryFontBold = await PdfGoogleFonts.cairoBold();

    final textDirection = isArabic
        ? pw.TextDirection.rtl
        : pw.TextDirection.ltr;
    final textAlignment = isArabic ? pw.TextAlign.right : pw.TextAlign.left;

    final themeData = pw.ThemeData.withFont(
      base: primaryFont,
      bold: primaryFontBold,
    );

    // Build colors
    final primaryTeal = PdfColor.fromHex(_brandTealHex);
    final cardBgColor = PdfColor.fromHex(_lightBgHex);

    doc.addPage(
      pw.MultiPage(
        theme: themeData,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        textDirection: textDirection,
        header: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(bottom: 20),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'SMARTFIT REPORT',
                  style: pw.TextStyle(
                    font: primaryFontBold,
                    fontSize: 12,
                    color: primaryTeal,
                    letterSpacing: 1.0,
                  ),
                ),
                pw.Text(
                  plan.generatedAt ??
                      DateTime.now().toString().substring(0, 10),
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.center,
            margin: const pw.EdgeInsets.only(top: 20),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by SmartFit AI Coach',
                  style: const pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey500,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey500,
                  ),
                ),
              ],
            ),
          );
        },
        build: (pw.Context context) {
          return [
            // Page 1: Branded Cover & Summary
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: cardBgColor,
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(12)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.stretch,
                children: [
                  pw.Text(
                    isArabic
                        ? 'تقرير صحتك البدنية الذكي'
                        : 'SmartFit Health Report',
                    style: pw.TextStyle(
                      font: primaryFontBold,
                      fontSize: 24,
                      color: primaryTeal,
                    ),
                    textAlign: textAlignment,
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    '${isArabic ? "الاسم" : "User"}: $userName',
                    style: pw.TextStyle(
                      font: primaryFontBold,
                      fontSize: 14,
                      color: PdfColors.grey800,
                    ),
                    textAlign: textAlignment,
                  ),
                  pw.SizedBox(height: 12),
                  pw.Divider(color: PdfColors.grey300),
                  pw.SizedBox(height: 12),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      _buildSummaryMetric(
                        isArabic ? 'الهدف البؤري' : 'Focus Zone',
                        plan.focusZone,
                        primaryFontBold,
                        primaryTeal,
                      ),
                      _buildSummaryMetric(
                        isArabic ? 'الكلوري اليومي' : 'Daily Calories',
                        '${plan.targetCaloriesKcal.round()} kcal',
                        primaryFontBold,
                        primaryTeal,
                      ),
                    ],
                  ),
                  pw.SizedBox(height: 16),
                  pw.Text(
                    isArabic
                        ? 'توزيع العناصر الغذائية الأساسية (الماكروز):'
                        : 'Daily Macronutrient Split:',
                    style: pw.TextStyle(
                      font: primaryFontBold,
                      fontSize: 12,
                      color: PdfColors.grey700,
                    ),
                    textAlign: textAlignment,
                  ),
                  pw.SizedBox(height: 6),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                    children: [
                      _buildMacroBadge(
                        isArabic ? 'بروتين' : 'Protein',
                        '${plan.macros.proteinG.round()}g',
                        '${plan.macros.proteinPct.round()}%',
                        primaryFontBold,
                      ),
                      _buildMacroBadge(
                        isArabic ? 'كربوهيدرات' : 'Carbs',
                        '${plan.macros.carbsG.round()}g',
                        '${plan.macros.carbsPct.round()}%',
                        primaryFontBold,
                      ),
                      _buildMacroBadge(
                        isArabic ? 'دهون' : 'Fat',
                        '${plan.macros.fatG.round()}g',
                        '${plan.macros.fatPct.round()}%',
                        primaryFontBold,
                      ),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            // Page 2: Workout Plan
            pw.Text(
              isArabic ? 'برنامج التدريب الرياضي' : 'Workout Program',
              style: pw.TextStyle(
                font: primaryFontBold,
                fontSize: 18,
                color: primaryTeal,
              ),
              textAlign: textAlignment,
            ),
            pw.SizedBox(height: 6),
            pw.Text(
              '${plan.preferredDays} ${isArabic ? "أيام في الأسبوع" : "Days per Week"} · ${plan.workoutSplit.length} ${isArabic ? "جلسات تدريبية" : "Sessions"}',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey600,
              ),
              textAlign: textAlignment,
            ),
            pw.SizedBox(height: 12),

            for (final day in plan.workoutSplit) ...[
              pw.Container(
                margin: const pw.EdgeInsets.only(bottom: 16),
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(8),
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.stretch,
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(
                          day.dayLabel,
                          style: pw.TextStyle(
                            font: primaryFontBold,
                            fontSize: 14,
                            color: primaryTeal,
                          ),
                        ),
                        pw.Text(
                          day.focusZone,
                          style: pw.TextStyle(
                            font: primaryFontBold,
                            fontSize: 12,
                            color: PdfColors.grey700,
                          ),
                        ),
                      ],
                    ),
                    if (day.note.isNotEmpty) ...[
                      pw.SizedBox(height: 4),
                      pw.Text(
                        day.note,
                        style: const pw.TextStyle(
                          fontSize: 10,
                          color: PdfColors.grey600,
                        ),
                        textAlign: textAlignment,
                      ),
                    ],
                    pw.SizedBox(height: 10),
                    pw.Table(
                      border: const pw.TableBorder(
                        horizontalInside: pw.BorderSide(
                          color: PdfColors.grey200,
                          width: 0.5,
                        ),
                      ),
                      children: [
                        pw.TableRow(
                          children: [
                            pw.Padding(
                              padding: const pw.EdgeInsets.symmetric(
                                vertical: 4,
                              ),
                              child: pw.Text(
                                isArabic ? 'التمرين' : 'Exercise',
                                style: pw.TextStyle(
                                  font: primaryFontBold,
                                  fontSize: 10,
                                ),
                              ),
                            ),
                            pw.Padding(
                              padding: const pw.EdgeInsets.symmetric(
                                vertical: 4,
                              ),
                              child: pw.Text(
                                isArabic
                                    ? 'المجموعات والتكرارات'
                                    : 'Sets & Reps',
                                style: pw.TextStyle(
                                  font: primaryFontBold,
                                  fontSize: 10,
                                ),
                              ),
                            ),
                            pw.Padding(
                              padding: const pw.EdgeInsets.symmetric(
                                vertical: 4,
                              ),
                              child: pw.Text(
                                isArabic ? 'المعدات المستهدفة' : 'Equipment',
                                style: pw.TextStyle(
                                  font: primaryFontBold,
                                  fontSize: 10,
                                ),
                              ),
                            ),
                          ],
                        ),
                        for (final ex in day.exercises)
                          pw.TableRow(
                            children: [
                              pw.Padding(
                                padding: const pw.EdgeInsets.symmetric(
                                  vertical: 6,
                                ),
                                child: pw.Text(
                                  ex.name,
                                  style: const pw.TextStyle(fontSize: 10),
                                ),
                              ),
                              pw.Padding(
                                padding: const pw.EdgeInsets.symmetric(
                                  vertical: 6,
                                ),
                                child: pw.Text(
                                  ex.setsRepsLabel,
                                  style: const pw.TextStyle(fontSize: 10),
                                ),
                              ),
                              pw.Padding(
                                padding: const pw.EdgeInsets.symmetric(
                                  vertical: 6,
                                ),
                                child: pw.Text(
                                  ex.equipment,
                                  style: const pw.TextStyle(fontSize: 10),
                                ),
                              ),
                            ],
                          ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
            pw.SizedBox(height: 24),

            // Page 3: Nutrition Plan
            pw.Text(
              isArabic ? 'خطة التغذية والوجبات' : 'Nutrition & Meal Plan',
              style: pw.TextStyle(
                font: primaryFontBold,
                fontSize: 18,
                color: primaryTeal,
              ),
              textAlign: textAlignment,
            ),
            pw.SizedBox(height: 12),

            for (final meal in plan.dailyMeals) ...[
              pw.Container(
                margin: const pw.EdgeInsets.only(bottom: 20),
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: cardBgColor,
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(8),
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.stretch,
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(
                          meal.displayName,
                          style: pw.TextStyle(
                            font: primaryFontBold,
                            fontSize: 14,
                            color: primaryTeal,
                          ),
                        ),
                        pw.Text(
                          '${meal.caloriesPerServing.round()} kcal',
                          style: pw.TextStyle(
                            font: primaryFontBold,
                            fontSize: 12,
                            color: PdfColors.grey700,
                          ),
                        ),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      '${isArabic ? "الوصفة" : "Recipe"}: ${meal.recipeName}',
                      style: pw.TextStyle(
                        font: primaryFontBold,
                        fontSize: 11,
                        color: PdfColors.grey800,
                      ),
                      textAlign: textAlignment,
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      'P: ${meal.proteinG.round()}g  ·  C: ${meal.carbsG.round()}g  ·  F: ${meal.fatG.round()}g',
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey600,
                      ),
                      textAlign: textAlignment,
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      isArabic ? 'المكونات:' : 'Ingredients:',
                      style: pw.TextStyle(font: primaryFontBold, fontSize: 10),
                      textAlign: textAlignment,
                    ),
                    pw.Text(
                      meal.ingredients,
                      style: const pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.grey800,
                      ),
                      textAlign: textAlignment,
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      isArabic ? 'طريقة التحضير:' : 'Instructions:',
                      style: pw.TextStyle(font: primaryFontBold, fontSize: 10),
                      textAlign: textAlignment,
                    ),
                    pw.Text(
                      meal.instructions,
                      style: const pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.grey800,
                      ),
                      textAlign: textAlignment,
                    ),
                  ],
                ),
              ),
            ],
          ];
        },
      ),
    );

    return doc.save();
  }

  /// Builds a vertical metric item for the cover summary block.
  static pw.Widget _buildSummaryMetric(
    String label,
    String value,
    pw.Font fontBold,
    PdfColor color,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label.toUpperCase(),
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          value,
          style: pw.TextStyle(font: fontBold, fontSize: 16, color: color),
        ),
      ],
    );
  }

  /// Builds a small macronutrient split badge.
  static pw.Widget _buildMacroBadge(
    String label,
    String weight,
    String percentage,
    pw.Font fontBold,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: const pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 2),
          pw.Text(
            weight,
            style: pw.TextStyle(
              font: fontBold,
              fontSize: 12,
              color: PdfColors.grey800,
            ),
          ),
          pw.Text(
            percentage,
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey500,
            ),
          ),
        ],
      ),
    );
  }

  /// Shares the PDF generated using Native dialog.
  static Future<void> sharePlanPdf(
    PlanResult plan,
    BuildContext context,
  ) async {
    try {
      final isArabic = Localizations.localeOf(context).languageCode == 'ar';
      final scaffold = ScaffoldMessenger.of(context);

      scaffold.showSnackBar(
        SnackBar(
          content: Text(
            isArabic ? 'جاري تحضير ملف PDF...' : 'Preparing PDF file...',
          ),
          duration: const Duration(seconds: 2),
        ),
      );

      final pdfBytes = await generatePlanPdf(plan, isArabic: isArabic);

      final tempDir = await getTemporaryDirectory();
      final filePath =
          '${tempDir.path}/smartfit_plan_${plan.planId ?? "active"}.pdf';
      final file = File(filePath);
      await file.writeAsBytes(pdfBytes);

      final box = context.findRenderObject() as RenderBox?;
      final sharePositionOrigin = box != null
          ? box.localToGlobal(Offset.zero) & box.size
          : Rect.zero;

      await SharePlus.instance.share(
        ShareParams(
          files: [XFile(filePath, mimeType: 'application/pdf')],
          subject: isArabic
              ? 'خطة صحتك البدنية من SmartFit'
              : 'Your SmartFit Personalized Plan',
          sharePositionOrigin: sharePositionOrigin,
        ),
      );
    } catch (e) {
      if (kDebugMode) print('Error sharing PDF: $e');
    }
  }

  /// Prints the PDF generated using Printing layout system.
  static Future<void> printPlanPdf(
    PlanResult plan,
    BuildContext context,
  ) async {
    try {
      final isArabic = Localizations.localeOf(context).languageCode == 'ar';
      final pdfBytes = await generatePlanPdf(plan, isArabic: isArabic);

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdfBytes,
        name: 'SmartFit_Plan_${plan.planId ?? "Active"}',
      );
    } catch (e) {
      if (kDebugMode) print('Error printing PDF: $e');
    }
  }
}
